### ISSUE TITLE
Incorrect Equation for Coin Flip Likelihood

### ISSUE THREAD

**Issue by RileyPaddock** [C0BBL3/assignment-problems#1]
In the part of your function where you return a string(when probability = None) you use the equation p^(num heads) * p^(num tails). You need to use p^(num heads) * (1-p)^(num tails)

**Comment by C0BBL3** [comment]
gonna fix it after the first period, I thought it did do p^(num heads) * (1-p)^(num tails), I must have spaced out when writing the code.

**Comment by C0BBL3** [comment]
fixed

**Comment by C0BBL3** [comment]
actually my code is fine;

`def probability_likelihood(heads_count, tails_count, probability=None):
    if probability != None:
        return round((probability ** heads_count) * (1 - probability)**tails_count, 5)
    else:
        return 'L(p) = p ^ ' + str(heads_count) + ' * p ^ ' + str(tails_count)`

the numbers are right it was the string in the else thats wrong. its fixed now.
