### ISSUE TITLE
Lines too long in Neuron

### ISSUE THREAD

**Issue by RileyPaddock** [C0BBL3/assignment-problems#3]
While I appreciate the whole class consisting of so little lines, a couple times it goes to far. Particularly on lines **10, 12, 38**.

**Comment by C0BBL3** [comment]
I agree that 38 is long, but it'll either be tall or wide, and I'm going with wide here, for lines 10 and 12 they're not even much longer than the first derivative function or the surrounding code so its fine.

**Comment by C0BBL3** [comment]
fixed
